FROM oven/bun:1.2.0
COPY --from=node:22.14.0 /usr/local/bin/node /usr/local/bin/node

ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GEMINI_API_KEY=${GEMINI_API_KEY}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
ENV TEBI_ACCESS_KEY=${TEBI_ACCESS_KEY}
ENV TEBI_SECRET_KEY=${TEBI_SECRET_KEY}
ENV TEBI_REGION=${TEBI_REGION}
ENV TEBI_BUCKET_NAME=${TEBI_BUCKET_NAME}
ENV TEBI_ENDPOINT_URL=${TEBI_ENDPOINT_URL}
ENV PORT=${PORT}
ENV CLIENT_URL=${CLIENT_URL}
ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/app/marklet-backend

COPY package.json .

RUN bun install

COPY . .

RUN apt-get update -y && apt-get install -y openssl

EXPOSE 0-5000

CMD ["bun", "start"]
